version: '3'
services:
  api:
    image: zrfinance/server:latest
    env_file: sso.env
    ports:
      - '9601:8000'
    volumes:
      - /var/logs/sso:/project/sso/logs
      - /var/nginx_upload:/project/sso/media
      - /var/logs/ssocron:/var/logs/sso
    restart: always
