version: '3'
services:
  api:
    image: zrfinance/nginx:latest
    ports:
      - '81:81'
    volumes:
      - /var/logs/nginx:/var/log/nginx
      - /var/static/nginx:/usr/local/nginx/html
      - /var/upload:/var/upload
    restart: always
